server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: user-netty

  rabbitmq:
    username: admin
    password: 123456
    host: localhost
    port: 5672