server:
  port: 8083
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
    store-type: REDIS
  redis:
    host: 172.20.10.14
    port: 6379
    password: 123456
    timeout: 1800000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
  rabbitmq:
    username: admin
    password: 123456
    host: localhost
    port: 5672
  application:
    name: user-oss
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


aliyun:
  oss:
    file:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tEg9gwD1vutiFsgAUbS
      keysecret: AXSshK3aTvTro5HrzwdlUjh7WLLAx3
      bucketname: bing-edu


email:
  fromEmail: verification_ice@qq.com
  password: yfjebidgptbpecff